name: CI/CD Micro Site Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# default permissions
permissions:
  contents: read

jobs:
  validate_and_build:
    name: Validate and Build Site
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Check Formatting 
        run: npm run format:check

      - name: Run Tests
        run: npm test

      - name: Static Analysis
        uses: actions/checkout@v6
        with:
         config: p/javascript

      - name: Run Smoke Tests
        run: npm run test:smoke

      - name: Build website
        run: |
          mkdir -p dist
          cp index.html dist/
          
      - name: Upload Deployment Artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'


  deploy:
    name: Deploy to GitHub Pages
    needs: validate_and_build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
